### ISSUE TITLE
[SR - task]Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by yeojoo1224** [yeojoo1224/Todo-App-homework#1]
## 만들고자 하는 기능

1. 회원가입 기능 
2. 로그인 기능
3. Todo 생성 기능
4. 캘린더 기능
5. Todo 리스트 체크 기능
6. 리스트 체크/미체크 여부를 바탕으로 달성률 표시

## 해당 기능을 구현하기 위해 할 일
1. [x] 회원 정보를 저장하는 db 구축
2. [x] Todo 리스트를 추가, 리스트에 라디오버튼 추가
3. [x] 오늘의 날짜, 캘린더 불러오는 코드 작성
4. [x] 리스트 체크 여부 저장 후 달성률 계산, 표시

## 예상 작업 시간
20h
